services:
  - type: web
    name: eduardokt-copa2026
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python -u app.py
    healthCheckPath: /api/status
    renderSubdomainPolicy: enabled
    autoDeployTrigger: commit
